# Generated by Django 4.2.30 on 2026-04-14 06:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='color',
            field=models.CharField(default='#4CAF50', max_length=7),
        ),
        migrations.AddField(
            model_name='account',
            name='credit_limit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='icon',
            field=models.CharField(default='bi-wallet2', max_length=50),
        ),
        migrations.AddField(
            model_name='account',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='savingsgoal',
            name='color',
            field=models.CharField(default='#4CAF50', max_length=7),
        ),
        migrations.AddField(
            model_name='savingsgoal',
            name='goal_type',
            field=models.CharField(choices=[('emergency', 'Emergency Fund'), ('vacation', 'Vacation'), ('purchase', 'Big Purchase'), ('investment', 'Investment'), ('debt', 'Debt Payoff'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='savingsgoal',
            name='icon',
            field=models.CharField(default='bi-piggy-bank', max_length=50),
        ),
        migrations.AlterField(
            model_name='savingsgoal',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('paused', 'Paused'), ('cancelled', 'Cancelled')], default='active', max_length=10),
        ),
        migrations.CreateModel(
            name='UserStreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_streak', models.IntegerField(default=0)),
                ('longest_streak', models.IntegerField(default=0)),
                ('last_logged', models.DateField(blank=True, null=True)),
                ('total_days_logged', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='streak', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
