# Generated by Django 4.2.30 on 2026-04-15 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_account_color_account_credit_limit_account_icon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes or details', null=True),
        ),
    ]
